version: '3'
services:

  backend:
    image: excelify-backend-prod-i
    container_name: excelify-backend-prod-c
    build:
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production

  frontend:
    image: excelify-frontend-prod-i
    container_name: excelify-frontend-prod-c
    build:
      dockerfile: Dockerfile.prod
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=production