version: '3'

services:
  backend:
    depends_on:
      - db
    build:
      context: ./backend
    environment:
      MONGO_URI: ${MONGO_URI}

  frontend:
    depends_on:
      - backend
    build:
      context: ./frontend

  db:
    image: mongo
    volumes:
      - db_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

volumes:
  db_data: